// apps/vite-react/src/App.tsx
import "./App.css";

import { Iconify } from "@monicon/react";

function App() {
  return (
    <main>
      <Iconify name="mdi:home" />
      <Iconify name="logos:active-campaign" />
      <Iconify name="logos:apache-superset-icon" />
      <Iconify name="invalid:icon" />
    </main>
  );
}

export default App;

// apps/vite-vue/src/App.vue
<script setup lang="ts">
import Iconify from "./components/Iconify.vue";
</script>

<template>
  <main>
    <Iconify name="mdi:home" :size="24" />
    <Iconify name="logos:active-campaign" />
    <Iconify name="logos:apache-superset-icon" />
    <Iconify name="invalid:icon" />
  </main>
</template>
