// apps/next/app/page.tsx
import { Iconify } from "@monicon/react";

import styles from "../styles/index.module.css";

export default function Web() {
  return (
    <main className={styles.container}>
      <Iconify name="mdi:home" />
      <Iconify name="logos:active-campaign" size={30} />
      <Iconify name="logos:apache-superset-icon" />
    </main>
  );
}

// apps/vite-vue/src/App.vue
<script setup lang="ts">
import Iconify from "./components/Iconify.vue";
</script>

<template>
  <main>
    <Iconify name="mdi:home" :size="24" />
    <Iconify name="logos:active-campaign" />
    <Iconify name="logos:apache-superset-icon" />
    <Iconify name="invalid:icon" />
  </main>
</template>
