// examples/nuxt-app/app.vue
<script setup lang="ts">
import BadgeCheckIcon from "@/components/icons/lucide/badge-check.vue";
import CloudDownloadIcon from "@/components/icons/lucide/cloud-download.vue";
import AccountIcon from "@/components/icons/mdi/account.vue";
import HomeIcon from "@/components/icons/mdi/home.vue";
import AtomIcon from "@/components/icons/logos/atom-icon.vue";
import ApacheLogo from "@/components/icons/logos/apache.vue";

useHead({
  title: "Nuxt App",
  meta: [{ name: "description", content: "Generated by create turbo" }],
});
</script>

<template>
  <main>
    <ApacheLogo color="white" width="50" />
    <BadgeCheckIcon color="white" width="50" />
    <CloudDownloadIcon color="white" width="50" />
    <AccountIcon color="white" width="50" />
    <HomeIcon color="white" width="50" />
    <AtomIcon color="white" width="50" />
  </main>
</template>

<style>
html,
body {
  margin: 0;
  padding: 0;
}

main {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
  background-color: #242424;
  color: rgba(255, 255, 255, 0.87);
  gap: 1rem;
}
</style>

// apps/rollup-react/src/App.jsx
import React from "react";

import BadgeCheckIcon from "./components/icons/lucide/badge-check";
import CloudDownloadIcon from "./components/icons/lucide/cloud-download";
import AccountIcon from "./components/icons/mdi/account";
import HomeIcon from "./components/icons/mdi/home";
import AtomIcon from "./components/icons/logos/atom-icon";
import ApacheLogo from "./components/icons/logos/apache";

const App = () => {
  return (
    <main
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
        backgroundColor: "black",
        gap: "1rem",
      }}
    >
      <ApacheLogo color="white" width={50} />
      <BadgeCheckIcon color="white" width={50} />
      <CloudDownloadIcon color="white" width={50} />
      <AccountIcon color="white" width={50} />
      <HomeIcon color="white" width={50} />
      <AtomIcon color="white" width={50} />
    </main>
  );
};

export default App;
