// examples/qwik-app/src/routes/index.tsx
import { component$ } from "@builder.io/qwik";
import type { DocumentHead } from "@builder.io/qwik-city";

import ApacheLogo from "~/components/icons/logos/apache";
import BadgeCheckIcon from "~/components/icons/lucide/badge-check";
import CloudDownloadIcon from "~/components/icons/lucide/cloud-download";
import AccountIcon from "~/components/icons/mdi/account";
import HomeIcon from "~/components/icons/mdi/home";
import AtomIcon from "~/components/icons/logos/atom-icon";

export default component$(() => {
  return (
    <div class="home">
      <ApacheLogo color="white" width={50} />
      <BadgeCheckIcon color="white" width={50} />
      <CloudDownloadIcon color="white" width={50} />
      <AccountIcon color="white" width={50} />
      <HomeIcon color="white" width={50} />
      <AtomIcon color="white" width={50} />
    </div>
  );
});

export const head: DocumentHead = {
  title: "Welcome to Qwik",
  meta: [
    {
      name: "description",
      content: "Qwik site description",
    },
  ],
};

// examples/svelte-app/src/routes/+page.svelte
<script>
	import BadgeCheckIcon from '$lib/components/icons/feather/activity.svelte';
	import CloudDownloadIcon from '$lib/components/icons/lucide/cloud-download.svelte';
	import AccountIcon from '$lib/components/icons/mdi/account.svelte';
	import HomeIcon from '$lib/components/icons/mdi/home.svelte';
	import AtomIcon from '$lib/components/icons/logos/atom-icon.svelte';
	import ApacheLogo from '$lib/components/icons/logos/apache.svelte';
</script>

<main>
	<BadgeCheckIcon height={50} />
	<CloudDownloadIcon height={50} />
	<AccountIcon height={50} />
	<HomeIcon height={50} />
	<AtomIcon height={50} />
	<ApacheLogo height={50} />
</main>

<style>
	:global(html),
	:global(body) {
		margin: 0;
		padding: 0;
	}

	main {
		display: flex;
		justify-content: center;
		align-items: center;
		height: 100vh;
		background-color: #242424;
		color: rgba(255, 255, 255, 0.87);
		gap: 20px;
	}
</style>
